### PR TITLE
YARA rule generator for LOLDrivers

### PR DESCRIPTION
**Pull request by Neo23x0**
This YARA rule generator creates YARA rules for the vulnerable / malicious drivers collected in the LOLDrivers project.

## How does it work? 

The generator processes the input samples and extract specific 'VersionInfo' values from the driver's PE headers. This includes e.g., the company name, file version, product version, description and other values. It then creates YARA rules that look for these specific values.

These YARA rules can then be used to:
- detect known vulnerable drivers that have a different hash (additional coverage); we'd run a retrohunt on Virustotal to find more of these drivers
- apply YARA rules in cases in which a hash calculation is not possible or feasible
- use a less strict version of the rules (see `--strict` flag) to detect the vulnerable drivers embedded in other files or loaded into memory

## Example Output

Example rule generated from the binaries in the `./drivers` folder.

```yara
rule PUA_VULN_Driver_NovellInc_NovellXTier_4qM7 {
	meta:
		description = "Detects vulnerable driver mentioned in LOLDrivers project using VersionInfo values from the PE header - ba2c0fa201c74621cddd8638497b3c70.bin, a1547e8b2ca0516d0d9191a55b8536c0.bin"
		author = "Florian Roth"
		reference = "https://github.com/magicsword-io/LOLDrivers"
		hash = "28999af32b55ddb7dcfc26376a244aa2fe297233ce7abe4919a1aef2f7e2cee7"
		hash = "ce23c2dae4cca4771ea50ec737093dfafac06c64db0f924a1ccbbf687e33f5a2"
		date = "2023-05-13"
		score = 50
	strings:
		$ = { 00460069006c0065004400650073006300720069007000740069006f006e[1-8]004e006f00760065006c006c002000580054006900650072002000530065007300730069006f006e0020004d0061006e0061006700650072 } /* FileDescription Novell XTier Session Manager */
		$ = { 0043006f006d00700061006e0079004e0061006d0065[1-8]004e006f00760065006c006c002c00200049006e0063002e } /* CompanyName Novell, Inc. */
		$ = { 00460069006c006500560065007200730069006f006e[1-8]0033002e0031002e0036002e0030 } /* FileVersion 3.1.6.0 */
		$ = { 00500072006f006400750063007400560065007200730069006f006e[1-8]0033002e0031002e0036 } /* ProductVersion 3.1.6 */
		$ = { 00500072006f0064007500630074004e0061006d0065[1-8]004e006f00760065006c006c002000580054006900650072 } /* ProductName Novell XTier */
		$ = { 004f0072006900670069006e0061006c00460069006c0065006e0061006d0065[1-8]006e00730063006d002e007300790073 } /* OriginalFilename nscm.sys */
		$ = { 004c006500670061006c0043006f0070007900720069006700680074[1-8]00280043002900200043006f007000790072006900670068007400200032003000300030002d0032003000300038002c0020004e006f00760065006c006c002c00200049006e0063002e00200041006c006c0020005200690067006800740073002000520065007300650072007600650064002e } /* LegalCopyright (C) Copyright 2000-2008, Novell, Inc. All Rights Reserved. */
	condition:
		uint16(0) == 0x5a4d and filesize < 100KB and all of them
}
```

### CODE REVIEW

**Comment by Neo23x0** [comment]
Strange I cannot push on that branch anymore 
Screenshot 2023-05-12 at 18 41 15

**Comment by josehelps** [comment]
@Neo23x0 I thnk this was due to a repo config setting for branch protection it was set to all branches. I just edited to just main. Should be ok now.

**Comment by Neo23x0** [comment]
Yeah, that worked

**Comment by josehelps** [comment]
@Neo23x0 I would move the requirements.txt libraries to the projects poetry and then update the instructions to use poetry. Also on the args, I would make the driver folder a required argument and maybe default to ../../drivers/ .. when I ran it without it throws an error: 
```
(loldrivers-4w9yDQSy-py3.10) jhernandez in ~/magicsword/LOLDrivers on yara-generator λ python bin/yara-generator/yara-generator.py           
Traceback (most recent call last):
  File "/home/jhernandez/magicsword/LOLDrivers/bin/yara-generator/yara-generator.py", line 239, in <module>
    Log.info("[+] Processing %d input paths" % len(args.d[0]))
TypeError: 'NoneType' object is not subscriptable
```

I already have all these changes in a local branch, happy to update this PR with these changes if you are ok with them.

**Comment by Neo23x0** [comment]
Yeah, please push it to the branch

**Pull request merged**
